from fpdf import FPDF
import tempfile
import cv2
import os


def sanitize_pdf_text(text):
    """Strip emoji and non-latin-1 characters so fpdf2 doesn't crash."""
    if not isinstance(text, str):
        return str(text)
    cleaned = ''
    for ch in text:
        try:
            ch.encode('latin-1')
            cleaned += ch
        except (UnicodeEncodeError, UnicodeDecodeError):
            cleaned += '?'
    # Normalize common unicode punctuation
    cleaned = (cleaned
               .replace('\u2013', '-').replace('\u2014', '--')
               .replace('\u201c', '"').replace('\u201d', '"')
               .replace('\u2018', "'").replace('\u2019', "'"))
    return cleaned


def generate_pdf_report(annotated_img, area, perimeter, tissues, indicators,
                        severity_score, severity_cat, narrative, rec):
    """Generate a downloadable PDF clinical assessment report."""
    pdf = FPDF()
    pdf.add_page()

    # -- Header --
    pdf.set_font("Arial", "B", 18)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 12, sanitize_pdf_text("ToxiGlow Wound Assessment Report"), ln=True, align="C")
    pdf.set_draw_color(0, 102, 204)
    pdf.line(10, 22, 200, 22)
    pdf.ln(8)

    # -- Date --
    from datetime import datetime
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(90, 109, 126)
    pdf.cell(0, 8, sanitize_pdf_text(
        f"Report generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"), ln=True)
    pdf.ln(4)

    # -- Annotated Image --
    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmp:
        cv2.imwrite(tmp.name, cv2.cvtColor(annotated_img, cv2.COLOR_RGB2BGR))
        img_path = tmp.name

    pdf.image(img_path, x=15, y=pdf.get_y(), w=85)

    # -- Metrics (right of image) --
    pdf.set_xy(110, pdf.get_y())
    pdf.set_font("Arial", "B", 13)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 10, sanitize_pdf_text(
        f"Severity Score: {severity_score}/100 ({severity_cat})"), ln=True)

    pdf.set_x(110)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, sanitize_pdf_text(f"Estimated Area: {area} cm2"), ln=True)
    pdf.set_x(110)
    pdf.cell(0, 8, sanitize_pdf_text(f"Perimeter: {perimeter} cm"), ln=True)

    pdf.set_x(110)
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 10, "Tissue Composition:", ln=True)
    pdf.set_font("Arial", "", 10)
    for t, p in tissues.items():
        if p > 0:
            pdf.set_x(115)
            pdf.cell(0, 7, sanitize_pdf_text(f"- {t}: {p:.1f}%"), ln=True)

    if indicators:
        pdf.set_x(110)
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 10, sanitize_pdf_text("Infection Markers:"), ln=True)
        pdf.set_font("Arial", "", 10)
        for ind in indicators:
            pdf.set_x(115)
            pdf.cell(0, 7, sanitize_pdf_text(f"- {ind}"), ln=True)

    # -- Clinical Narrative --
    pdf.set_xy(15, max(pdf.get_y(), 135))
    pdf.ln(4)
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 10, "Clinical Narrative:", ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, sanitize_pdf_text(narrative))
    pdf.ln(4)

    # -- Recommendation --
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 10, sanitize_pdf_text(f"Recommendation ({rec['tier']}):"), ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, sanitize_pdf_text(rec["text"]))

    # -- Disclaimer --
    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(143, 163, 181)
    pdf.multi_cell(
        0, 5,
        sanitize_pdf_text(
            "Disclaimer: This report is generated by ToxiGlow for informational purposes only. "
            "It does not constitute a medical diagnosis. Always consult a qualified healthcare "
            "provider for wound care decisions."
        ),
    )

    # fpdf2 >= 2.7 output(dest="S") returns bytearray; older returns str
    raw = pdf.output(dest="S")
    if isinstance(raw, (bytes, bytearray)):
        pdf_bytes = bytes(raw)
    else:
        pdf_bytes = raw.encode("latin-1", errors="replace")

    try:
        os.remove(img_path)
    except OSError:
        pass

    return pdf_bytes
